table dim_direct_cust
	lineageTag: a32cef6c-e2b6-4ec1-8cbb-a2fe00d06f4b

	column cust_id
		dataType: string
		lineageTag: f8566eb8-38b9-4b02-86c3-2dfe6f2c3a15
		summarizeBy: none
		sourceColumn: cust_id

		annotation SummarizationSetBy = Automatic

	column cust_key
		dataType: string
		lineageTag: 359a4c33-063b-4be6-8ff2-fa3cf9a053d2
		summarizeBy: none
		sourceColumn: cust_key

		annotation SummarizationSetBy = Automatic

	column local_customer_name
		dataType: string
		lineageTag: 8390a613-77e6-4eab-9997-b57a50bf7ee2
		summarizeBy: none
		sourceColumn: local_customer_name

		annotation SummarizationSetBy = Automatic

	column parent_local_customer_name
		dataType: string
		lineageTag: e7766964-a433-493c-9c11-3506596410c3
		summarizeBy: none
		sourceColumn: parent_local_customer_name

		annotation SummarizationSetBy = Automatic

	column sub_channel
		dataType: string
		lineageTag: 94d0c74e-2678-4288-b9fe-68579f525499
		summarizeBy: none
		sourceColumn: sub_channel

		annotation SummarizationSetBy = Automatic

	partition dim_direct_cust = m
		mode: import
		queryGroup: Dimension
		source =
				let
				    Source = Databricks.Catalogs(#"Prod Server", #"Prod HTTP Path", [Catalog=null, Database=null, EnableAutomaticProxyDiscovery=null]),
				    cdl_amhq_prod_Database = Source{[Name = "cdl_amhq_prod",Kind="Database"]}[Data],
				    nexa_msv_workbench_gold_Schema = cdl_amhq_prod_Database{[Name="nexa_msv_workbench_gold",Kind="Schema"]}[Data],
				    vn_cust_dim_Table = nexa_msv_workbench_gold_Schema{[Name="vn_cust_dim",Kind="Table"]}[Data],
				    #"Changed Type" = Table.TransformColumnTypes(vn_cust_dim_Table,{{"cust_key", type text}}),
				    #"Removed Columns" = Table.RemoveColumns(#"Changed Type",{"update_date", "insert_date", "ama_last_processed_date", "customer_lv2_name"}),
				    #"Removed Other Columns" = Table.SelectColumns(#"Removed Columns",{"cust_id", "cust_key", "local_customer_name", "parent_local_customer_name"}),
				    #"Added Custom" = Table.AddColumn(#"Removed Other Columns", "sub_channel", each if [local_customer_name] = null then "Others"
				        else if [local_customer_name] = "BACH HOA XANH" then "Bach Hoa Xanh"
				        else if Text.Contains([local_customer_name], "EMART", Comparer.OrdinalIgnoreCase) then "Emart"
				        else if Text.Contains([local_customer_name], "BIG C", Comparer.OrdinalIgnoreCase) then "CRV"
				        else if Text.Contains([local_customer_name], "COOP", Comparer.OrdinalIgnoreCase) then "Coop"
				        else if Text.Contains([local_customer_name], "CO-OP", Comparer.OrdinalIgnoreCase) then "Coop"
				        else if Text.Contains([local_customer_name], "MEGA", Comparer.OrdinalIgnoreCase) then "Mega Market"
				        else if Text.Contains([local_customer_name], "LOTTE", Comparer.OrdinalIgnoreCase) then "Lotte"
				        else if Text.Contains([local_customer_name], "AEON", Comparer.OrdinalIgnoreCase) then "Aeon"
				        else if Text.Contains([local_customer_name], "GIANT", Comparer.OrdinalIgnoreCase) then "Giant"
				        else if Text.Contains([local_customer_name], "MESA POC", Comparer.OrdinalIgnoreCase) then "Mesa POC"
				        else if Text.Contains([local_customer_name], "eMesa", Comparer.OrdinalIgnoreCase) then "eMesa"
				        else if Text.Contains([local_customer_name], "MESA", Comparer.OrdinalIgnoreCase) then "Mesa"
				        else if Text.Contains([local_customer_name], "TUAN VIET", Comparer.OrdinalIgnoreCase) then "Tuan Viet"
				        else if Text.Contains([local_customer_name], "DAC HUNG", Comparer.OrdinalIgnoreCase) then "Dac Hung"
				        else if Text.Contains([local_customer_name], "PHU THAI", Comparer.OrdinalIgnoreCase) then "Phu Thai"
				        else if Text.Contains([local_customer_name], "VIET LIEN", Comparer.OrdinalIgnoreCase) then "Viet Lien"
				        else if Text.Contains([local_customer_name], "Partner", Comparer.OrdinalIgnoreCase) then "Brand Partner"
				        else "Others")
				in
				    #"Added Custom"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

