table dim_sub_channel
	lineageTag: f1dabfd2-8d9e-4f8f-a74a-537a9a682c3c

	column channel
		dataType: string
		lineageTag: 3b193eca-e6dc-49f0-951c-1d57e6b98f52
		summarizeBy: none
		sourceColumn: channel

		annotation SummarizationSetBy = Automatic

	column sub_channel
		dataType: string
		lineageTag: 413274a9-bbe6-436c-b6f3-87241b0d13e1
		summarizeBy: none
		sourceColumn: sub_channel
		sortByColumn: sort

		changedProperty = SortByColumn

		annotation SummarizationSetBy = Automatic

	column sort
		dataType: int64
		formatString: 0
		lineageTag: 40d0c577-5e9f-4d8a-a647-4c475c499819
		summarizeBy: sum
		sourceColumn: sort

		annotation SummarizationSetBy = Automatic

	partition dim_sub_channel = m
		mode: import
		queryGroup: Dimension
		source =
				let
				    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("bZFNb4MwDIb/SsS5h4XSbj22jA1pMFBBZVLVg8uiBg2SiYG0nz+btJKHeolfP3E+Xvt49OKXwlt4z1CLeDQXlNI7LW44VT+AwWco16MoNTQolwyXIxhxaNSAOph40UHbnu0vgh3UWsQWxAcYjflqXlA1poOezq7nW++2H7Q4QwumVpg/zgsKO/4reHK/KlLUW2UNhg1D4f5AJh84svabmGQsscNAt0mfwVRdQKTQf0025ZJtRdf/y4DB1wbMBJ3hqLYdlbognVV17fEtSmfwbVth4lbpLO16MJ8ix3eM6qmrs1xu7pbRvSLPQpqjc01jEkmjqDVc+3z0SU6ETz6dCB96MZGAkcqhFUNZGUd7gmsGw4xWH72e/gA=", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [channel = _t, sub_channel = _t, sort = _t]),
				    #"Changed Type" = Table.TransformColumnTypes(Source,{{"channel", type text}, {"sub_channel", type text}, {"sort", Int64.Type}})
				in
				    #"Changed Type"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

