table dim_product
	lineageTag: ac8f1ef9-b718-493c-b06e-852498f62b0b

	column prod_key
		dataType: string
		lineageTag: 39d310ae-053c-41a5-84f4-1581581f45bb
		summarizeBy: none
		sourceColumn: prod_key

		annotation SummarizationSetBy = Automatic

	column product_name
		dataType: string
		lineageTag: e6822aee-69d2-4fb5-bc84-c5be24e57d9a
		summarizeBy: none
		sourceColumn: product_name

		annotation SummarizationSetBy = Automatic

	column product_barcode_name
		dataType: string
		lineageTag: c87c8eb5-2b2d-4d2e-acf6-4343391dbfba
		summarizeBy: none
		sourceColumn: product_barcode_name

		annotation SummarizationSetBy = Automatic

	column fpc_id
		dataType: string
		lineageTag: bdc870c8-fd9d-4d3f-837b-70e6f12a094b
		summarizeBy: none
		sourceColumn: fpc_id

		annotation SummarizationSetBy = Automatic

	column gtin_item_0
		dataType: string
		lineageTag: 41adaf68-bef1-432a-be59-73c00263d73e
		summarizeBy: none
		sourceColumn: gtin_item_0

		annotation SummarizationSetBy = Automatic

	column gtin_case
		dataType: string
		lineageTag: 99cd7ad1-7729-4e17-8391-304ca997210c
		summarizeBy: none
		sourceColumn: gtin_case

		annotation SummarizationSetBy = Automatic

	column category
		dataType: string
		lineageTag: b399bb90-13da-4a70-b120-6ee5b12e53be
		summarizeBy: none
		sourceColumn: category

		annotation SummarizationSetBy = Automatic

	column category_h5005
		dataType: string
		lineageTag: 66f3e12d-8387-48b4-ac31-4ee2b1533c37
		summarizeBy: none
		sourceColumn: category_h5005

		annotation SummarizationSetBy = Automatic

	column brand_H5005
		dataType: string
		lineageTag: 239f0d63-d2a1-49d0-8ee9-2af904e1bc53
		summarizeBy: none
		sourceColumn: brand_H5005

		annotation SummarizationSetBy = Automatic

	column brand_detail_H5005
		dataType: string
		lineageTag: 01d11c7c-826d-43bd-92a7-6cc7fd9c2be5
		summarizeBy: none
		sourceColumn: brand_detail_H5005

		annotation SummarizationSetBy = Automatic

	column fpc_name_h5005
		dataType: string
		lineageTag: 18d0c5aa-3031-4fcf-b099-894076cfebad
		summarizeBy: none
		sourceColumn: fpc_name_h5005

		annotation SummarizationSetBy = Automatic

	column brand_element_h5005
		dataType: string
		lineageTag: 297f42c0-75b9-409f-89cc-bc65dc5b2fb7
		summarizeBy: none
		sourceColumn: brand_element_h5005

		annotation SummarizationSetBy = Automatic

	column brand
		dataType: string
		lineageTag: 070547ee-b29d-4839-8535-2d195f32aad3
		summarizeBy: none
		sourceColumn: brand

		annotation SummarizationSetBy = Automatic

	column form
		dataType: string
		lineageTag: 42d1feed-5966-42cc-881a-1f0ae579f68f
		summarizeBy: none
		sourceColumn: form

		annotation SummarizationSetBy = Automatic

	column brand_form
		dataType: string
		lineageTag: 5fd0f9eb-4451-4aab-8700-4c2e3d57682d
		summarizeBy: none
		sourceColumn: brand_form

		annotation SummarizationSetBy = Automatic

	column size
		dataType: string
		lineageTag: 9b3f2a1b-4360-46ae-8c86-443b2a82c137
		summarizeBy: none
		sourceColumn: size

		annotation SummarizationSetBy = Automatic

	column variant
		dataType: string
		lineageTag: 0324ba52-5b5a-4a74-a822-94a15da95203
		summarizeBy: none
		sourceColumn: variant

		annotation SummarizationSetBy = Automatic

	column vn_prod_name
		dataType: string
		lineageTag: 385ab4bf-d256-49ac-b243-16f944efc9d4
		summarizeBy: none
		sourceColumn: vn_prod_name

		annotation SummarizationSetBy = Automatic

	column vn_sub_category_name
		dataType: string
		lineageTag: 2514af0f-7a2f-441a-8451-db34151b57d1
		summarizeBy: none
		sourceColumn: vn_sub_category_name

		annotation SummarizationSetBy = Automatic

	column vn_local_sub_brand_form
		dataType: string
		lineageTag: abda41a3-f6a1-44d3-9729-7c9f25df7f54
		summarizeBy: none
		sourceColumn: vn_local_sub_brand_form

		annotation SummarizationSetBy = Automatic

	column vn_size_group_name
		dataType: string
		lineageTag: 335588f5-6b6c-46ba-88a3-b042b2c7f180
		summarizeBy: none
		sourceColumn: vn_size_group_name

		annotation SummarizationSetBy = Automatic

	column vn_local_package_size
		dataType: string
		lineageTag: 4a41b329-0297-4bdd-8ea2-92ef2b3bd67a
		summarizeBy: none
		sourceColumn: vn_local_package_size

		annotation SummarizationSetBy = Automatic

	column vn_local_variant_2_name
		dataType: string
		lineageTag: 40fbfb39-d2b5-4d95-ae88-0609d0cf86f6
		summarizeBy: none
		sourceColumn: vn_local_variant_2_name

		annotation SummarizationSetBy = Automatic

	column vn_pack_type_name
		dataType: string
		lineageTag: 19a0ca2d-8e57-42b3-9e1d-03709bc1fc4e
		summarizeBy: none
		sourceColumn: vn_pack_type_name

		annotation SummarizationSetBy = Automatic

	column vn_pack_size_name
		dataType: string
		lineageTag: 1d6084e8-455a-482c-9ccd-b624de399ada
		summarizeBy: none
		sourceColumn: vn_pack_size_name

		annotation SummarizationSetBy = Automatic

	column vn_local_sku_type_2
		dataType: string
		lineageTag: 0b57dd5f-6878-4de1-81ca-82c431c9e261
		summarizeBy: none
		sourceColumn: vn_local_sku_type_2

		annotation SummarizationSetBy = Automatic

	column vn_local_company
		dataType: string
		lineageTag: 5417f3d8-6171-45d2-a259-b45d2b6da7c4
		summarizeBy: none
		sourceColumn: vn_local_company

		annotation SummarizationSetBy = Automatic

	column vn_segment_name
		dataType: string
		lineageTag: b6786c39-7a5a-435c-ab55-2c2f2cd996b7
		summarizeBy: none
		sourceColumn: vn_segment_name

		annotation SummarizationSetBy = Automatic

	column vn_item_height
		dataType: double
		lineageTag: 6b8fad6f-711c-4a91-9189-a598661d6b85
		summarizeBy: sum
		sourceColumn: vn_item_height

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column vn_item_width
		dataType: double
		lineageTag: c8af031d-c937-4570-a6cd-935799a2288e
		summarizeBy: sum
		sourceColumn: vn_item_width

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column vn_item_depth
		dataType: double
		lineageTag: a5c36ad1-c836-4d45-b386-bb4b3fc9a202
		summarizeBy: sum
		sourceColumn: vn_item_depth

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column vn_psku_name
		dataType: string
		lineageTag: 4b3ccbaa-c072-459f-96c1-ab32be9074e7
		summarizeBy: none
		sourceColumn: vn_psku_name

		annotation SummarizationSetBy = Automatic

	column vn_tier_name
		dataType: string
		lineageTag: ac437284-64f9-427b-aa79-4c937dc6eb7e
		summarizeBy: none
		sourceColumn: vn_tier_name

		annotation SummarizationSetBy = Automatic

	column vn_local_pg_equivalent
		dataType: string
		lineageTag: 7bb48811-603b-40b2-92ed-79c4dbe0f44f
		summarizeBy: none
		sourceColumn: vn_local_pg_equivalent

		annotation SummarizationSetBy = Automatic

	column vn_prod_alter_lang_name
		dataType: string
		lineageTag: 3624034c-c2ad-4d6b-ad22-7a4bb69813f3
		summarizeBy: none
		sourceColumn: vn_prod_alter_lang_name

		annotation SummarizationSetBy = Automatic

	column vn_local_sku_type_1
		dataType: string
		lineageTag: 558b95ea-3734-44a8-bc0c-8cc82c6d8429
		summarizeBy: none
		sourceColumn: vn_local_sku_type_1

		annotation SummarizationSetBy = Automatic

	column update_date
		dataType: dateTime
		formatString: General Date
		lineageTag: 95bbf67c-f2b9-4a30-afad-7a9718d51a59
		summarizeBy: none
		sourceColumn: update_date

		variation Variation
			isDefault
			relationship: bffd3f2c-f54a-4239-9b29-e192969d7a91
			defaultHierarchy: LocalDateTable_40588dba-1d55-4fd1-9335-e8df5100cf93.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	column insert_date
		dataType: dateTime
		formatString: General Date
		lineageTag: 6389f965-133b-4769-972e-d10c978999f2
		summarizeBy: none
		sourceColumn: insert_date

		variation Variation
			isDefault
			relationship: cb99d83e-8034-4f99-b3c9-3e2c42c2a537
			defaultHierarchy: LocalDateTable_cf7384c1-17ac-49c7-af09-96b84f4b8ad1.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	column ama_last_processed_date
		dataType: dateTime
		formatString: General Date
		lineageTag: a4237ca5-db57-4164-b973-5499d3f081c0
		summarizeBy: none
		sourceColumn: ama_last_processed_date

		variation Variation
			isDefault
			relationship: df8bde90-6a9c-4235-9522-1512fda9a3a3
			defaultHierarchy: LocalDateTable_b4447a94-2bad-439a-ab0b-ad35cf793595.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	column brand_form_h5005
		dataType: string
		lineageTag: b714c8f5-339c-441b-aa12-c314af71a13d
		summarizeBy: none
		sourceColumn: brand_form_h5005

		annotation SummarizationSetBy = Automatic

	column local_standard_form
		dataType: string
		lineageTag: dd72f481-0e8a-4d75-948c-d2bc52a8412e
		summarizeBy: none
		sourceColumn: local_standard_form

		annotation SummarizationSetBy = Automatic

	partition dim_product = m
		mode: import
		queryGroup: Dimension
		source =
				let
				    Source = Databricks.Catalogs(#"Prod Server", #"Prod HTTP Path", [Catalog=null, Database=null, EnableAutomaticProxyDiscovery=null]),
				    cdl_amhq_prod_Database = Source{[Name = "cdl_amhq_prod",Kind="Database"]}[Data],
				    nexa_msv_workbench_gold_Schema = cdl_amhq_prod_Database{[Name="nexa_msv_workbench_gold",Kind="Schema"]}[Data],
				    vn_product_dim_Table = nexa_msv_workbench_gold_Schema{[Name="vn_product_dim",Kind="Table"]}[Data],
				    #"Renamed Columns" = Table.RenameColumns(vn_product_dim_Table,{{"gtin_item", "gtin_item_0"}}),
				    #"Changed Type" = Table.TransformColumnTypes(#"Renamed Columns",{{"prod_key", type text}}),
				    #"Appended Query" = Table.Combine({#"Changed Type", vn_product_by_gtin_dim_vw})
				in
				    #"Appended Query"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

