table dim_indirect_store_hist
	lineageTag: c940193e-5833-4cd2-a4a8-406b4119d3b5

	column store_code
		dataType: string
		lineageTag: dd8e21fc-b64d-4bc8-aa40-17506f456196
		summarizeBy: none
		sourceColumn: store_code

		annotation SummarizationSetBy = Automatic

	column store_id
		dataType: string
		lineageTag: 88160393-b2ae-49ca-8cbd-5eaa9caf6e85
		summarizeBy: none
		sourceColumn: store_id

		annotation SummarizationSetBy = Automatic

	column sub_channel_name
		dataType: string
		lineageTag: bd6ca3ea-316c-466b-a616-de3883fe8504
		summarizeBy: none
		sourceColumn: sub_channel_name

		annotation SummarizationSetBy = Automatic

	column sub_channel
		dataType: string
		lineageTag: 04983226-3d37-4b78-aa43-cf650cade8aa
		summarizeBy: none
		sourceColumn: sub_channel

		annotation SummarizationSetBy = Automatic

	column channel_name
		dataType: string
		lineageTag: b154c382-5e17-4519-b399-1151a0baa430
		summarizeBy: none
		sourceColumn: channel_name

		annotation SummarizationSetBy = Automatic

	column distributor_local_channel_name
		dataType: string
		lineageTag: c7a7a4f9-d92f-43df-8e84-be1f37d900b0
		summarizeBy: none
		sourceColumn: distributor_local_channel_name

		annotation SummarizationSetBy = Automatic

	column store_key
		dataType: string
		lineageTag: 8681e622-a447-43be-b235-ced2323b7305
		summarizeBy: none
		sourceColumn: store_key

		annotation SummarizationSetBy = Automatic

	column site_trade_channel_key
		dataType: string
		lineageTag: a9544a5d-480a-4beb-858e-f568f477fd7c
		summarizeBy: none
		sourceColumn: site_trade_channel_key

		annotation SummarizationSetBy = Automatic

	column store_name
		dataType: string
		lineageTag: 02a61b60-3c95-433e-b212-d9215c3dea65
		summarizeBy: none
		sourceColumn: store_name

		annotation SummarizationSetBy = Automatic

	column source_store_id
		dataType: string
		lineageTag: 7db1d16c-c434-4e58-8083-ed2c192e407d
		summarizeBy: none
		sourceColumn: source_store_id

		annotation SummarizationSetBy = Automatic

	column seller_id
		dataType: string
		lineageTag: 9fe73563-be12-4f71-9277-6d93e139efdb
		summarizeBy: none
		sourceColumn: seller_id

		annotation SummarizationSetBy = Automatic

	column branch_id
		dataType: string
		lineageTag: 9078d455-fc45-4cdd-a67c-bb29cfad6a04
		summarizeBy: none
		sourceColumn: branch_id

		annotation SummarizationSetBy = Automatic

	column branch_name
		dataType: string
		lineageTag: cfc84673-3819-440e-a35e-badd2813e4d4
		summarizeBy: none
		sourceColumn: branch_name

		annotation SummarizationSetBy = Automatic

	column local_customer_name
		dataType: string
		lineageTag: ff7a0a8d-ea86-4864-9672-be71e99e1163
		summarizeBy: none
		sourceColumn: local_customer_name

		annotation SummarizationSetBy = Automatic

	column branch_key = dim_indirect_store_hist[branch_id] & dim_indirect_store_hist[store_code]
		lineageTag: d42d3b2c-a87e-450c-b76a-8aa3ed2485e1
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column begin_date
		dataType: dateTime
		formatString: Long Date
		lineageTag: 6adf5234-c533-467d-b2c8-9169f025ab33
		summarizeBy: none
		sourceColumn: begin_date

		variation Variation
			isDefault
			relationship: 814ca6a2-2d77-489b-8258-ebbcbb7c2cdd
			defaultHierarchy: LocalDateTable_48304a35-fa8d-4419-b00c-edf895f0d23f.'Date Hierarchy'

		changedProperty = DataType

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	partition dim_indirect_store_hist = m
		mode: import
		queryGroup: Dimension
		source =
				let
				    Source = Value.NativeQuery(Databricks.Catalogs("adb-1405689875182560.0.azuredatabricks.net", "sql/protocolv1/o/1405689875182560/0428-061324-1bphpcbr", [Catalog="cdl_amhq_prod", Database=null, EnableAutomaticProxyDiscovery=null, Implementation=null]){[Name="cdl_amhq_prod",Kind="Database"]}[Data], "WITH hist_tbl AS (#(lf)    SELECT DISTINCT#(lf)        store_code,#(lf)        store_id,#(lf)        store_key,#(lf)        sub_channel_name,#(lf)        sub_channel,#(lf)        channel_name,#(lf)        distributor_local_channel_name,#(lf)        site_trade_channel_key,#(lf)        begin_date                          -- ← sửa từ last_update → begin_date#(lf)    FROM (#(lf)        SELECT #(lf)            site_id                        AS store_code,#(lf)            site_key                       AS store_id,#(lf)            sub_channel_name,#(lf)            CASE#(lf)                WHEN sub_channel_name = 'WHOLESALER: HYPER/ SUPER/ HFS'    THEN 'WSP'#(lf)                WHEN sub_channel_name = 'LARGE TRADITIONAL STORE (HFS)'    THEN 'LP'#(lf)                WHEN sub_channel_name = 'MEDIUM TRADITIONAL STORE (HFS)'   THEN 'MP'#(lf)                WHEN sub_channel_name IN ('SMALL TRADITIONAL STORE (HFS)', #(lf)                                          'KIOSK (HFS)')                   THEN 'SP'#(lf)                WHEN sub_channel_name = 'WHOLESALER:  SPECIALTY RETAIL'    THEN 'KAW'#(lf)                WHEN sub_channel_name = 'SPECIALTY BEAUTY'                 THEN 'COS'#(lf)                ELSE 'OTHER'#(lf)            END                            AS sub_channel,#(lf)            channel_name,#(lf)            distributor_local_channel_name,#(lf)            site_hist_key                  AS store_key,#(lf)            site_trade_channel_key,#(lf)            begin_date#(lf)        FROM nexa_msv_workbench.site_dim_hist_vw#(lf)        WHERE data_provider_key = 10000000000011#(lf)          AND ama_active_flag = 'true'#(lf)        QUALIFY ROW_NUMBER() OVER (#(lf)            PARTITION BY site_key,#(lf)                         site_id,#(lf)                         sub_channel_name,#(lf)                         site_trade_channel_key,#(lf)                         channel_name#(lf)            ORDER BY begin_date DESC#(lf)        ) = 1#(lf)    )#(lf)),#(lf)#(lf)dim_store AS (#(lf)    SELECT#(lf)        s.store_id,#(lf)        s.store_name,#(lf)        s.source_store_id,#(lf)        s.seller_id,#(lf)        b.branch_id,#(lf)        b.branch_name,#(lf)        c.local_customer_name#(lf)    FROM (#(lf)        SELECT#(lf)            store_id,#(lf)            store_name,#(lf)            store_code       AS source_store_id,#(lf)            route_identifier AS seller_id#(lf)        FROM nexa_msv_workbench_gold.vn_store_dim#(lf)    ) s#(lf)    LEFT JOIN nexa_msv_workbench_gold.vn_branch_dim_vw b#(lf)        ON s.store_id = b.store_key#(lf)    LEFT JOIN nexa_msv_workbench_gold.vn_cust_dim c#(lf)        ON b.cust_key = c.cust_key#(lf))#(lf)#(lf)SELECT#(lf)    h.store_code,#(lf)    h.store_id,#(lf)    h.store_key,#(lf)    h.sub_channel_name,#(lf)    h.sub_channel,#(lf)    h.channel_name,#(lf)    h.distributor_local_channel_name,#(lf)    h.site_trade_channel_key,#(lf)    h.begin_date,    #(lf)    s.store_name,#(lf)    s.source_store_id,#(lf)    s.seller_id,#(lf)    s.branch_id,#(lf)    s.branch_name,#(lf)    s.local_customer_name#(lf)FROM hist_tbl h#(lf)LEFT JOIN dim_store s ON h.store_id = s.store_id#(lf)WHERE s.branch_id IS NOT NULL#(lf)  AND s.branch_id != ''", null, [EnableFolding=true]),
				    #"Changed Type" = Table.TransformColumnTypes(Source,{{"site_trade_channel_key", type text}, {"store_name", type text}, {"source_store_id", type text}, {"seller_id", type text}, {"branch_id", type text}, {"branch_name", type text}, {"local_customer_name", type text}, {"store_id", type text}, {"store_key", type text}})
				in
				    #"Changed Type"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Exception

