table dim_customer_share_value
	lineageTag: d5fb038b-1a7c-404d-94b5-2603c4b6a9d7

	column customer
		dataType: string
		lineageTag: f37dcc43-f6ca-4798-9bc2-d79d72f3caa7
		summarizeBy: none
		sourceColumn: customer

		annotation SummarizationSetBy = Automatic

	column Sort
		dataType: int64
		formatString: 0
		lineageTag: a0d364e7-7554-4bdf-b7f1-56660c32a03a
		summarizeBy: sum
		sourceColumn: Sort

		annotation SummarizationSetBy = Automatic

	column channel
		dataType: string
		lineageTag: e882c844-0566-47e1-8d7a-dff51707738b
		summarizeBy: none
		sourceColumn: channel

		annotation SummarizationSetBy = Automatic

	partition dim_customer_share_value = m
		mode: import
		queryGroup: Dimension
		source =
				let
				    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("i45W8knMU3DOyFTSUTIE4uDcxJycpPwKpVidaKXwzLzcxKISoLARupRjan4eUMwYiD2CfcFCrlC1JhCxmDywqHNQGJBvChUrgonm5xcAhczQhH1T0xMVfBOLslNBBpmjyfrkl5SkAsUskMVjAQ==", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [customer = _t, Sort = _t, channel = _t]),
				    #"Changed Type" = Table.TransformColumnTypes(Source,{{"Sort", Int64.Type}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

