table fct_psku_pos
	lineageTag: 54cb489a-b176-4f9c-8d3d-37f05f397773

	column year_month
		dataType: string
		lineageTag: 5826ef77-f6d0-4332-84af-ad85d6a87607
		summarizeBy: none
		sourceColumn: year_month

		annotation SummarizationSetBy = Automatic

	column store_id
		dataType: string
		lineageTag: a9d7b2d7-cecc-49b2-8542-17bcc67fc37b
		summarizeBy: none
		sourceColumn: store_id

		annotation SummarizationSetBy = Automatic

	column store_code
		dataType: string
		lineageTag: 610a9170-775c-4b72-92c8-e5b90df33a19
		summarizeBy: none
		sourceColumn: store_code

		annotation SummarizationSetBy = Automatic

	column customer
		dataType: string
		lineageTag: 38cbd45d-d8eb-4b85-b901-94ef39cb401d
		summarizeBy: none
		sourceColumn: customer

		annotation SummarizationSetBy = Automatic

	column local_segment
		dataType: string
		lineageTag: d6f08173-8b07-438b-868d-209859fb9a50
		summarizeBy: none
		sourceColumn: local_segment

		annotation SummarizationSetBy = Automatic

	column sub_channel
		dataType: string
		lineageTag: c81f6590-648c-4afc-902b-d4affb573dde
		summarizeBy: none
		sourceColumn: sub_channel

		annotation SummarizationSetBy = Automatic

	column key_seg_month
		dataType: string
		lineageTag: 119e5894-5461-4d0e-b8f4-7cbc85295e65
		summarizeBy: none
		sourceColumn: key_seg_month

		annotation SummarizationSetBy = Automatic

	column date
		dataType: dateTime
		formatString: Long Date
		lineageTag: e5a56613-cdf2-49b6-9a7e-7c217c31b0b6
		summarizeBy: none
		sourceColumn: date

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column gtin_item
		dataType: string
		lineageTag: b014ad7e-7654-400f-9bf3-8ec37f24e2da
		summarizeBy: none
		sourceColumn: gtin_item

		annotation SummarizationSetBy = Automatic

	column segmentation
		dataType: string
		lineageTag: 90b38842-b92d-4d7f-8f5e-68377e974a91
		summarizeBy: none
		sourceColumn: segmentation

		annotation SummarizationSetBy = Automatic

	column gtin_name
		dataType: string
		lineageTag: c3d8397e-5140-4743-972b-b73e74e241e1
		summarizeBy: none
		sourceColumn: gtin_name

		annotation SummarizationSetBy = Automatic

	column psku
		dataType: string
		lineageTag: 54bfbf07-467b-499e-b3c6-167d7aa51419
		summarizeBy: none
		sourceColumn: psku

		annotation SummarizationSetBy = Automatic

	column psku_code
		dataType: string
		lineageTag: 984e58c4-2b7a-4eb5-a70c-34cdf8584a75
		summarizeBy: none
		sourceColumn: psku_code

		annotation SummarizationSetBy = Automatic

	column DGP_P3M_Sellout_pos = ```
			
			VAR P3M_date = EDATE(fct_psku_pos[date],-2)
			VAR _pos_monthly = 
			CALCULATE(
			    SUM(vn_pos_monthly[sales_qty]),
			    FILTER(
			        ALL(vn_pos_monthly),
			        fct_psku_pos[gtin_item] = vn_pos_monthly[gtin_item] &&
			        fct_psku_pos[store_code] = vn_pos_monthly[store_code] &&
			        vn_pos_monthly[date] >= P3M_date &&
			        vn_pos_monthly[date] <= fct_psku_pos[date]
			    ))
			VAR _pos_coop = 
			CALCULATE(
			    SUM(vn_pos_coop[sales_qty]),
			    FILTER(
			        ALL(vn_pos_coop),
			        fct_psku_pos[gtin_item] = vn_pos_coop[gtin_code] &&
			        fct_psku_pos[store_code] = vn_pos_coop[store_code] &&
			        vn_pos_coop[date] >= P3M_date &&
			        vn_pos_coop[date] <= fct_psku_pos[date]
			    ))
			VAR _pos_crv = 
			CALCULATE(
			    SUM(vn_pos_crv[sales_qty]),
			    FILTER(
			        ALL(vn_pos_crv),
			        fct_psku_pos[gtin_item] = vn_pos_crv[gtin_code] &&
			        fct_psku_pos[store_code] = vn_pos_crv[store_code] &&
			        vn_pos_crv[date] >= P3M_date &&
			        vn_pos_crv[date] <= fct_psku_pos[date]
			    ))
			RETURN
			_pos_monthly + _pos_coop + _pos_crv
			```
		lineageTag: ebb3af02-95c2-4b8e-9499-e6a9d75def4e
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column DGP_Inventory =
			
			VAR P3M_date = EDATE(fct_psku_pos[date],-2)
			RETURN
			CALCULATE(
			    SUM(fct_psku_inventory[inventory_qty]),
			    FILTER(
			        ALL(fct_psku_inventory),
			        fct_psku_inventory[gtin_item] = fct_psku_pos[gtin_item] &&
			        fct_psku_inventory[store_key] = fct_psku_pos[store_code] &&
			        fct_psku_inventory[date] >= P3M_date &&
			        fct_psku_inventory[date] <= fct_psku_pos[date]
			    ))
		formatString: 0
		lineageTag: 93195a93-abdf-4c4b-9ed1-e5f8802774a7
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

	column DGP_P3M =
			
			IF(
			    fct_psku_pos[sub_channel] IN {"Bach Hoa Xanh", "Winmart"}, fct_psku_pos[DGP_P3M_Sellout_pos] + fct_psku_pos[DGP_Inventory],
			    fct_psku_pos[DGP_P3M_Sellout_pos]
			)
		lineageTag: 2b79d41a-8fb0-4030-8ffe-b55c5a6cceaf
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	partition fct_psku_pos = m
		mode: import
		queryGroup: Fact
		source =
				let
				    Source = pos_store_fulltime,
				    #"Added Custom" = Table.AddColumn(Source, "key_seg_month", each [year_month]&[local_segment]),
				    #"Merged Queries" = Table.NestedJoin(#"Added Custom", {"key_seg_month"}, fct_psku, {"key_seg_month"}, "fct_psku", JoinKind.LeftOuter),
				    #"Expanded fct_psku" = Table.ExpandTableColumn(#"Merged Queries", "fct_psku", {"date", "gtin_item", "segmentation", "gtin_name", "psku_code", "psku", "year_month", "key_seg_month"}, {"date", "gtin_item", "segmentation", "gtin_name", "psku_code", "psku", "year_month.1", "key_seg_month.1"}),
				    #"Filtered Rows" = Table.SelectRows(#"Expanded fct_psku", each [key_seg_month.1] <> null and [key_seg_month.1] <> ""),
				    #"Removed Columns" = Table.RemoveColumns(#"Filtered Rows",{"year_month.1", "key_seg_month.1"})
				in
				    #"Removed Columns"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

