table fct_dgp_smartsell
	lineageTag: b601b1f9-9fb1-4bbe-933a-8246ec0fc20a

	column yearmonth
		dataType: string
		lineageTag: b48f1409-d6e8-4fcd-b33c-909fc1ab0851
		summarizeBy: none
		sourceColumn: yearmonth

		annotation SummarizationSetBy = Automatic

	column date
		dataType: dateTime
		formatString: Long Date
		lineageTag: c6903608-2181-49db-a099-9541416dd06a
		summarizeBy: none
		sourceColumn: date

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column store_id
		dataType: string
		lineageTag: 663a0d35-57ac-486e-b5f9-353a1f08bf73
		summarizeBy: none
		sourceColumn: store_id

		annotation SummarizationSetBy = Automatic

	column gtin_item
		dataType: string
		lineageTag: cf98c74e-ff62-4b4a-9e12-ae75aef2d43c
		summarizeBy: none
		sourceColumn: gtin_item

		annotation SummarizationSetBy = Automatic

	column actual_smartsell
		dataType: int64
		formatString: 0
		lineageTag: 9b8d347b-7fd9-4ed6-b086-259ce498353d
		summarizeBy: sum
		sourceColumn: actual_smartsell

		annotation SummarizationSetBy = Automatic

	column target_smartsell
		dataType: int64
		formatString: 0
		lineageTag: 4ad29198-b7b3-48fc-8169-d9f050c88aed
		summarizeBy: sum
		sourceColumn: target_smartsell

		annotation SummarizationSetBy = Automatic

	column sub_channel
		dataType: string
		lineageTag: 96f68830-5298-4cd6-a388-402325dddd60
		summarizeBy: none
		sourceColumn: sub_channel

		annotation SummarizationSetBy = Automatic

	column pr_key
		dataType: string
		lineageTag: a3dc8706-e2dc-4965-9912-dccca310416b
		summarizeBy: none
		sourceColumn: pr_key

		annotation SummarizationSetBy = Automatic

	column customer
		dataType: string
		lineageTag: e31c9cc3-b833-4f8a-99f1-d0b85a1fbe1a
		summarizeBy: none
		sourceColumn: customer

		annotation SummarizationSetBy = Automatic

	column local_segment
		dataType: string
		lineageTag: b7dbf6ce-c269-46de-9c77-576470b8be72
		summarizeBy: none
		sourceColumn: local_segment

		annotation SummarizationSetBy = Automatic

	partition fct_dgp_smartsell = m
		mode: import
		queryGroup: Fact
		source =
				let
				    Source = Databricks.Catalogs(#"Prod Server", #"Prod HTTP Path", [Catalog=null, Database=null, EnableAutomaticProxyDiscovery=null]),
				    cdl_amhq_prod_Database = Source{[Name = "cdl_amhq_prod",Kind="Database"]}[Data],
				    nexa_msv_workbench_gold_Schema = cdl_amhq_prod_Database{[Name="nexa_msv_workbench_gold",Kind="Schema"]}[Data],
				    vn_sfdc_sf_dgp_fct_Table = nexa_msv_workbench_gold_Schema{[Name="vn_sfdc_sf_dgp_fct",Kind="Table"]}[Data],
				    #"Changed Type" = Table.TransformColumnTypes(vn_sfdc_sf_dgp_fct_Table,{{"gtin_item", Int64.Type}}),
				    #"Changed Type1" = Table.TransformColumnTypes(#"Changed Type",{{"gtin_item", type text}}),
				    #"Removed Other Columns" = Table.SelectColumns(#"Changed Type1",{"visitdate", "store_id", "yearmonth", "gtin_item", "actual_smartsell", "target_smartsell", "actual_pos_sellout", "target_pos_sellout", "actual_pos_inventory", "target_pos_inventory", "customer_id"}),
				    #"Renamed Columns" = Table.RenameColumns(#"Removed Other Columns",{{"visitdate", "date"}}),
				    #"Removed Other Columns1" = Table.SelectColumns(#"Renamed Columns",{"date", "store_id", "yearmonth", "gtin_item", "actual_smartsell", "target_smartsell"}),
				    #"Merged Queries" = Table.NestedJoin(#"Removed Other Columns1", {"store_id"}, dim_pos_store, {"store_id"}, "pos_store", JoinKind.LeftOuter),
				    #"Expanded pos_store" = Table.ExpandTableColumn(#"Merged Queries", "pos_store", {"pr_key", "customer", "local_segment", "sub_channel"}, {"pr_key", "customer", "local_segment", "sub_channel"}),
				    #"Filtered Rows" = Table.SelectRows(#"Expanded pos_store", each ([sub_channel] = "North balance" or [sub_channel] = "South balance")),
				    #"Removed Duplicates" = Table.Distinct(#"Filtered Rows")
				in
				    #"Removed Duplicates"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Exception

