table fct_qdgp
	lineageTag: 7595610e-20bd-416b-b87d-8a9745a72f20

	column Segment
		dataType: string
		lineageTag: 72461a2c-72e0-46ee-8ee6-19ce1aaf0b10
		summarizeBy: none
		sourceColumn: Segment

		annotation SummarizationSetBy = Automatic

	column Local_Segment
		dataType: string
		lineageTag: b25692e8-f7ff-4412-8cb3-1ae7dfefa7bd
		summarizeBy: none
		sourceColumn: Local_Segment

		annotation SummarizationSetBy = Automatic

	column SKUCode
		dataType: string
		lineageTag: 2e5488ee-0521-416b-92bb-4811fd72fd3f
		summarizeBy: none
		sourceColumn: SKUCode

		annotation SummarizationSetBy = Automatic

	column GroupCode
		dataType: string
		lineageTag: d4374192-dab4-4724-9b5e-8cdcc93edee7
		summarizeBy: none
		sourceColumn: GroupCode

		annotation SummarizationSetBy = Automatic

	column GroupName
		dataType: string
		lineageTag: 13ed28d3-ee52-46dd-8fd8-b54b7eab3d87
		summarizeBy: none
		sourceColumn: GroupName

		annotation SummarizationSetBy = Automatic

	column Category
		dataType: string
		lineageTag: 6a2bb1f3-358c-4f78-a675-f4e694856bb9
		summarizeBy: none
		sourceColumn: Category

		annotation SummarizationSetBy = Automatic

	column Region
		dataType: string
		lineageTag: 9a5d04c0-be3f-4340-b8e2-2b345bf19aa5
		summarizeBy: none
		sourceColumn: Region

		annotation SummarizationSetBy = Automatic

	column 'MOQ (IT)'
		dataType: int64
		formatString: 0
		lineageTag: 59b46fab-47c7-419a-9b11-91727ccbe768
		summarizeBy: none
		sourceColumn: MOQ (IT)

		annotation SummarizationSetBy = Automatic

	column ApplyForMonth
		dataType: string
		lineageTag: b1fa60d3-1791-4e2a-b18a-87483003d6cb
		summarizeBy: none
		sourceColumn: ApplyForMonth

		annotation SummarizationSetBy = Automatic

	column ApplyFrom
		dataType: string
		lineageTag: b2b6616a-c5ca-436d-9536-8c017761c9d7
		summarizeBy: none
		sourceColumn: ApplyFrom

		annotation SummarizationSetBy = Automatic

	column ApplyTo
		dataType: string
		lineageTag: f45d1d07-604b-4ae4-a54a-b9a941c104df
		summarizeBy: none
		sourceColumn: ApplyTo

		annotation SummarizationSetBy = Automatic

	column QDGP_Region_ClassID
		dataType: string
		lineageTag: cc65a38c-3452-4b4c-9e17-717be8be497f
		summarizeBy: none
		sourceColumn: QDGP_Region_ClassID

		annotation SummarizationSetBy = Automatic

	column QDGP_Group_Key
		dataType: string
		lineageTag: 5939ebf6-2a05-4bce-b021-59e0e64928a9
		summarizeBy: none
		sourceColumn: QDGP_Group_Key

		annotation SummarizationSetBy = Automatic

	column QDGP_Group_GCAS
		dataType: string
		lineageTag: 4b7c7440-d7e1-49f2-a1e1-b9bbc57ccbc8
		summarizeBy: none
		sourceColumn: QDGP_Group_GCAS

		annotation SummarizationSetBy = Automatic

	column 'English GroupName'
		dataType: string
		lineageTag: 6b127718-338f-4f3c-b39f-33f60fe3d530
		summarizeBy: none
		sourceColumn: English GroupName

		annotation SummarizationSetBy = Automatic

	column key_qdgp = fct_qdgp[ApplyForMonth] & "_" & fct_qdgp[QDGP_Group_GCAS]
		lineageTag: 031ee2eb-ba4a-4963-bf42-a93872595558
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	partition fct_qdgp = m
		mode: import
		queryGroup: Dimension
		source =
				let
				    Source = SharePoint.Files("https://pgone.sharepoint.com/sites/ITPG", [ApiVersion = 15]),
				    #"Filtered Rows" = Table.SelectRows(Source, each ([Name] = "MD_QDGP.csv")),
				    #"MD_QDGP csv_https://pgone sharepoint com/sites/ITPG/Shared Documents/Document/8  NEXA (IMPORTANT_DO NOT CHANGE)/Master Data Ingestion/" = #"Filtered Rows"{[Name="MD_QDGP.csv",#"Folder Path"="https://pgone.sharepoint.com/sites/ITPG/Shared Documents/Document/8. NEXA (IMPORTANT_DO NOT CHANGE)/Master Data Ingestion/"]}[Content],
				    #"Imported CSV" = Csv.Document(#"MD_QDGP csv_https://pgone sharepoint com/sites/ITPG/Shared Documents/Document/8  NEXA (IMPORTANT_DO NOT CHANGE)/Master Data Ingestion/",[Delimiter=",", Columns=11, Encoding=65001, QuoteStyle=QuoteStyle.None]),
				    #"Promoted Headers" = Table.PromoteHeaders(#"Imported CSV", [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"Segment", type text}, {"Local_Segment", type text}, {"SKUCode", type text}, {"GroupCode", type text}, {"GroupName", type text}, {"Category", type text}, {"Region", type text}, {"MOQ (IT)", Int64.Type},{"ApplyForMonth", type text}}),
				    #"Removed Duplicates" = Table.Distinct(#"Changed Type"),
				    #"Added Custom1" = Table.AddColumn(#"Removed Duplicates", "QDGP_Region_ClassID", each [Region] &"_"& [Local_Segment]),
				    #"Added Custom" = Table.AddColumn(#"Added Custom1", "QDGP_Group_Key", each [Local_Segment] &"_"&[Region] &"_"&[GroupCode]),
				    #"Added Custom2" = Table.AddColumn(#"Added Custom", "QDGP_Group_GCAS", each [Region] &"_"& [Local_Segment] &"_"& [SKUCode]),
				    #"Merged Queries" = Table.NestedJoin(#"Added Custom2", {"GroupName","ApplyForMonth"}, qdgp_english_convert, {"GroupName", "ApplyForMonth"}, "QDGP-English Group Name", JoinKind.LeftOuter),
				    #"Expanded QDGP-English Group Name" = Table.ExpandTableColumn(#"Merged Queries", "QDGP-English Group Name", {"English GroupName"}, {"QDGP-English Group Name.English GroupName"}),
				    #"Renamed Columns" = Table.RenameColumns(#"Expanded QDGP-English Group Name",{{"QDGP-English Group Name.English GroupName", "English GroupName"}})
				in
				    #"Renamed Columns"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

