table 'Scenario Selection DataType'
	lineageTag: 50a4fcab-886c-41a6-a856-440af3a2de81

	column Typ_ID
		dataType: string
		lineageTag: 8a042a29-0331-4dbd-8907-f76cb066c94d
		summarizeBy: none
		sourceColumn: Typ_ID

		annotation SummarizationSetBy = Automatic

	column Typ_Name
		dataType: string
		lineageTag: 73f55a1e-295c-46ba-8856-3879c0306e4e
		summarizeBy: none
		sourceColumn: Typ_Name

		annotation SummarizationSetBy = Automatic

	column Typ_DisplayName
		dataType: string
		lineageTag: b3916335-96af-4523-99ea-1a33ac51ca86
		summarizeBy: none
		sourceColumn: Typ_DisplayName

		annotation SummarizationSetBy = Automatic

	column 'Typ_Display Name Alt.'
		dataType: string
		lineageTag: 0535681b-4b81-44d3-9317-b2d4b4e08571
		summarizeBy: none
		sourceColumn: Typ_Display Name Alt.

		annotation SummarizationSetBy = Automatic

	partition 'Scenario Selection DataType' = m
		mode: import
		queryGroup: Parameter
		source =
				let
				    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("i45WMlTSUQpLzClNxaBjdaKVjEC8/JzS3FQsDJACYyA3KMTFGY0CSZkAOQH+wSgkSNwUyHZxD0AhQeJmQHYgRAiZAkmZAznBYEMQJEjcAsx2QSFB4pYgR4KNQJAgcUMDIMcTLIQgwRKgYHDOL0stSkxPxcEEqwMFiHt+TkpqnkJxSX5RKgEuWA8ojPxDFJwyc3L0XRIr8fJiYwE=", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [Typ_ID = _t, Typ_Name = _t, Typ_DisplayName = _t, #"Typ_Display Name Alt." = _t])
				in
				    Source

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

