table share_value_fct_total
	lineageTag: 3eef15fd-495e-4100-83e1-6c8cc37bd82d

	column customer
		dataType: string
		lineageTag: aef552a9-8138-4b7b-ade2-f28e0975c399
		summarizeBy: none
		sourceColumn: customer

		annotation SummarizationSetBy = Automatic

	column date
		dataType: dateTime
		formatString: Short Date
		lineageTag: 226c477f-78fc-47e5-83e7-34382b092845
		summarizeBy: none
		sourceColumn: date

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column category
		dataType: string
		lineageTag: f94e5a4d-49cf-474e-a264-a0241fde0564
		summarizeBy: none
		sourceColumn: category

		annotation SummarizationSetBy = Automatic

	column value
		dataType: double
		formatString: #,0
		lineageTag: d69e818e-fe93-4448-995d-af279553ea7e
		summarizeBy: sum
		sourceColumn: value

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isDecimal":true}

	partition share_value_fct_total = m
		mode: import
		queryGroup: Fact
		source =
				let
				    Source = PowerPlatform.Dataflows(),
				    Workspaces = Source{[Id="Workspaces"]}[Data],
				    #"d5309721-c5fc-4d37-924d-0b134d285358" = Workspaces{[workspaceId="d5309721-c5fc-4d37-924d-0b134d285358"]}[Data],
				    #"c2702488-9142-4872-83de-e36ced0eee99" = #"d5309721-c5fc-4d37-924d-0b134d285358"{[dataflowId="c2702488-9142-4872-83de-e36ced0eee99"]}[Data],
				    vn_smallbox_value_share_ = #"c2702488-9142-4872-83de-e36ced0eee99"{[entity="vn_smallbox_value_share",version=""]}[Data],
				    #"Filtered Rows" = Table.SelectRows(vn_smallbox_value_share_, each ([Customer] = "Lan Chi - Total" or [Customer] = "Total Vin")),
				    #"Replaced Value" = Table.ReplaceValue(#"Filtered Rows","LAN CHI","Lan Chi",Replacer.ReplaceText,{"Agency"}),
				    #"Replaced Value1" = Table.ReplaceValue(#"Replaced Value","Total Vin","Winmart",Replacer.ReplaceText,{"Agency"}),
				    #"Removed Columns" = Table.RemoveColumns(#"Replaced Value1",{"Customer"}),
				    #"Renamed Columns" = Table.RenameColumns(#"Removed Columns",{{"Agency", "customer"}, {"Attribute", "date"}}),
				    #"Removed Columns1" = Table.RemoveColumns(#"Renamed Columns",{"CAT"}),
				    #"Renamed Columns1" = Table.RenameColumns(#"Removed Columns1",{{"Category (modified)", "category"}}),
				    #"Added Custom" = Table.AddColumn(#"Renamed Columns1", "value", each [Value]*1000000),
				    #"Changed Type" = Table.TransformColumnTypes(#"Added Custom",{{"value", type number}}),
				    #"Removed Columns2" = Table.RemoveColumns(#"Changed Type",{"Value"}),
				    #"Appended Query" = Table.Combine({#"Removed Columns2", share_value_fct_hsm_total})
				in
				    #"Appended Query"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

