table sos_sod_fct_hsm
	lineageTag: d75579c3-d533-4bc4-8e18-ab419da9a6ff

	column visit_id
		dataType: string
		lineageTag: 7c4aa980-ad5e-40e8-a198-24b75e4bac37
		summarizeBy: none
		sourceColumn: visit_id

		annotation SummarizationSetBy = Automatic

	column visit_date
		dataType: dateTime
		formatString: Short Date
		lineageTag: 29e6d063-ec4f-4619-a646-d7be0a9d5080
		summarizeBy: none
		sourceColumn: visit_date

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column store_id
		dataType: string
		lineageTag: ceab3051-209c-404b-b352-a298bdbf5469
		summarizeBy: none
		sourceColumn: store_id

		annotation SummarizationSetBy = Automatic

	column brand
		dataType: string
		lineageTag: 3102a660-2dbd-45de-95fc-e63266e84237
		summarizeBy: none
		sourceColumn: brand

		annotation SummarizationSetBy = Automatic

	column type
		dataType: string
		lineageTag: 03e3e9d6-0d85-4266-832f-52bd8c5541b5
		summarizeBy: none
		sourceColumn: type

		annotation SummarizationSetBy = Automatic

	column year_month = YEAR(sos_sod_fct_hsm[visit_date])&"M"&FORMAT(sos_sod_fct_hsm[visit_date],"MM")
		lineageTag: 06194101-24bf-457c-9a40-674067af4622
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column category
		dataType: string
		lineageTag: 3bc9f14d-f5e4-4b85-a1f7-3e5a623040bd
		summarizeBy: none
		sourceColumn: category

		annotation SummarizationSetBy = Automatic

	column category_total
		dataType: string
		lineageTag: 213240e0-dca3-468a-bb68-5afea11ba44a
		summarizeBy: none
		sourceColumn: category_total

		annotation SummarizationSetBy = Automatic

	column own
		dataType: int64
		formatString: 0
		lineageTag: 45f35bba-7add-4198-afdf-72c97cfc3114
		summarizeBy: sum
		sourceColumn: own

		annotation SummarizationSetBy = Automatic

	column linear
		dataType: double
		lineageTag: 5796cd51-2455-4d3e-88d6-1aa3ee68dda6
		summarizeBy: sum
		sourceColumn: linear

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	partition sos_sod_fct_hsm = m
		mode: import
		queryGroup: Fact
		source =
				let
				    Source = PowerPlatform.Dataflows(null),
				    Workspaces = Source{[Id="Workspaces"]}[Data],
				    #"d5309721-c5fc-4d37-924d-0b134d285358" = Workspaces{[workspaceId="d5309721-c5fc-4d37-924d-0b134d285358"]}[Data],
				    #"eeb7231a-7987-44b3-ba05-113c028de0b2" = #"d5309721-c5fc-4d37-924d-0b134d285358"{[dataflowId="eeb7231a-7987-44b3-ba05-113c028de0b2"]}[Data],
				    #"vn_ir_sos_sod_view (dataflow)_" = #"eeb7231a-7987-44b3-ba05-113c028de0b2"{[entity="vn_ir_sos_sod_view (dataflow)",version=""]}[Data],
				    #"Merged Queries" = Table.NestedJoin(#"vn_ir_sos_sod_view (dataflow)_", {"product_id"}, dim_ir_product, {"product_id"}, "dim_ir_product", JoinKind.LeftOuter),
				    #"Expanded dim_ir_product" = Table.ExpandTableColumn(#"Merged Queries", "dim_ir_product", {"base", "brand", "Category_Shipment", "type"}, {"category", "brand", "category_total", "type"}),
				    #"Filtered Rows1" = Table.SelectRows(#"Expanded dim_ir_product", each ([brand] <> "Technical Brand")),
				    #"Removed Other Columns" = Table.SelectColumns(#"Filtered Rows1",{"visit_id", "own", "linear", "visit_date", "internal_code", "category", "brand", "category_total", "type"}),
				    #"Renamed Columns" = Table.RenameColumns(#"Removed Other Columns",{{"internal_code", "store_id"}})
				in
				    #"Renamed Columns"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

