table vn_busines_target_LP
	lineageTag: d3a33ef3-086e-47d6-a5fd-783ae6d3d00d

	column 'Year Month'
		dataType: string
		lineageTag: 50ae3b92-ac42-414d-b194-0ba299bb4c93
		summarizeBy: none
		sourceColumn: Year Month

		annotation SummarizationSetBy = Automatic

	column BranchCodeNumber
		dataType: string
		lineageTag: 653fa283-b153-4fa0-973f-a98c8c580931
		summarizeBy: none
		sourceColumn: BranchCodeNumber

		annotation SummarizationSetBy = Automatic

	column RetailerCode
		dataType: string
		lineageTag: 812a0a21-f6cf-4f91-ab60-ee00071504a5
		summarizeBy: none
		sourceColumn: RetailerCode

		annotation SummarizationSetBy = Automatic

	column 'LP Type'
		dataType: string
		lineageTag: 1693a6e0-5a7e-4d8c-a7f5-729d4332c7d5
		summarizeBy: none
		sourceColumn: LP Type

		annotation SummarizationSetBy = Automatic

	column 'Cut off All'
		dataType: int64
		formatString: 0
		lineageTag: 48178118-9ba5-4307-b08e-41c2c8736f05
		summarizeBy: sum
		sourceColumn: Cut off All

		annotation SummarizationSetBy = Automatic

	column pr_key =
			
			VAR _key = vn_busines_target_LP[BranchCodeNumber] & vn_busines_target_LP[RetailerCode]
			RETURN
			LOOKUPVALUE(
			    dim_indirect_store[pr_key],
			    dim_indirect_store[seller_key],
			    _key
			)
		lineageTag: 645dc8b8-c4ad-44c5-b8bc-7e06a77fa77a
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column date = ```
			DATE(LEFT(vn_busines_target_LP[Year Month],4), RIGHT(vn_busines_target_LP[Year Month],2),1) 
			```
		formatString: Short Date
		lineageTag: 170544d7-d46f-4d5b-807b-1ab16d6c71ca
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column 'DGP Target'
		dataType: int64
		formatString: 0
		lineageTag: aa441b67-d811-4534-a3f7-786ff2b1714a
		summarizeBy: sum
		sourceColumn: DGP Target

		annotation SummarizationSetBy = Automatic

	partition vn_busines_target_LP = m
		mode: import
		queryGroup: Fact
		source =
				let
				    Source = PowerBI.Dataflows(),
				    #"d5309721-c5fc-4d37-924d-0b134d285358" = Source{[workspaceId="d5309721-c5fc-4d37-924d-0b134d285358"]}[Data],
				    #"2d85e630-3b5d-44fd-bd8b-26501ead176c" = #"d5309721-c5fc-4d37-924d-0b134d285358"{[dataflowId="2d85e630-3b5d-44fd-bd8b-26501ead176c"]}[Data],
				    #"LP Target" = #"2d85e630-3b5d-44fd-bd8b-26501ead176c"{[entity="LP Target"]}[Data],
				    #"Removed Columns" = Table.RemoveColumns(#"LP Target",{"Source.Name"}),
				    #"Changed Type" = Table.TransformColumnTypes(#"Removed Columns",{{"DGP Target", Int64.Type}, {"Cut-off (LP target + Silver incentive)", Int64.Type}, {"Cut off LP (incentive)", Int64.Type}, {"Cut off All", Int64.Type}}),
				    #"Removed Other Columns" = Table.SelectColumns(#"Changed Type",{"Year Month", "BranchCodeNumber", "RetailerCode", "LP Type", "Cut off All", "DGP Target"}),
				    #"Filtered Rows" = Table.SelectRows(#"Removed Other Columns", each [Year Month] <> null and [Year Month] <> "")
				in
				    #"Filtered Rows"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

