table vn_business_target_distributor_storeswise
	lineageTag: fb154a27-324d-4d77-b93f-fdd5130a405f

	column Date
		dataType: dateTime
		formatString: Short Date
		lineageTag: 374c324b-7828-4521-9cb9-48396e9c6924
		summarizeBy: none
		sourceColumn: Date

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Corp Distributor ID'
		dataType: string
		lineageTag: b9f90dc9-6c13-48e9-8de2-b1ffcd413bf2
		summarizeBy: none
		sourceColumn: Corp Distributor ID

		annotation SummarizationSetBy = Automatic

	column 'Corp Distributor Branch ID'
		dataType: string
		lineageTag: 1175f666-1424-4e84-a976-185708f38ac2
		summarizeBy: none
		sourceColumn: Corp Distributor Branch ID

		annotation SummarizationSetBy = Automatic

	column 'Source Store ID'
		dataType: string
		lineageTag: bba2ec00-5237-465e-a52d-b8a7b3d6986b
		summarizeBy: none
		sourceColumn: Source Store ID

		annotation SummarizationSetBy = Automatic

	column 'Sales Target'
		dataType: int64
		formatString: #,0
		lineageTag: 53be0df0-8263-49e7-8af2-2706ddd36afc
		summarizeBy: sum
		sourceColumn: Sales Target

		annotation SummarizationSetBy = Automatic

	column 'DGP P3M Target'
		dataType: int64
		formatString: 0
		lineageTag: e3434823-3810-4fc8-a7dc-fb691910e546
		summarizeBy: sum
		sourceColumn: DGP P3M Target

		annotation SummarizationSetBy = Automatic

	column pr_key =
			
			VAR _key = vn_business_target_distributor_storeswise[Corp Distributor Branch ID] & vn_business_target_distributor_storeswise[Source Store ID]
			RETURN
			LOOKUPVALUE(
			    dim_indirect_store[pr_key],
			    dim_indirect_store[seller_key],
			    _key
			)
		lineageTag: 84453c72-aa65-42f0-8adb-e6790c953b36
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	partition vn_business_target_distributor_storeswise = m
		mode: import
		queryGroup: Fact
		source =
				let
				    Source = PowerPlatform.Dataflows(null),
				    Workspaces = Source{[Id="Workspaces"]}[Data],
				    #"d5309721-c5fc-4d37-924d-0b134d285358" = Workspaces{[workspaceId="d5309721-c5fc-4d37-924d-0b134d285358"]}[Data],
				    #"645719f5-b0c7-4d3a-8202-07c5f68bbb5c" = #"d5309721-c5fc-4d37-924d-0b134d285358"{[dataflowId="645719f5-b0c7-4d3a-8202-07c5f68bbb5c"]}[Data],
				    Query_ = #"645719f5-b0c7-4d3a-8202-07c5f68bbb5c"{[entity="Query",version=""]}[Data],
				    #"Removed Other Columns" = Table.SelectColumns(Query_,{"Date", "Corp Distributor ID", "Corp Distributor Branch ID", "Source Store ID", "Sales Target", "DGP P3M Target"}),
				    #"Split Column by Delimiter" = Table.SplitColumn(Table.TransformColumnTypes(#"Removed Other Columns", {{"Date", type text}}, "en-US"), "Date", Splitter.SplitTextByDelimiter("/", QuoteStyle.Csv), {"Date.1", "Date.2", "Date.3"}),
				    #"Changed Type" = Table.TransformColumnTypes(#"Split Column by Delimiter",{{"Date.1", Int64.Type}, {"Date.2", Int64.Type}, {"Date.3", Int64.Type}}),
				    #"Renamed Columns" = Table.RenameColumns(#"Changed Type",{{"Date.1", "Month"}, {"Date.2", "Day"}, {"Date.3", "Year"}}),
				    #"Merged Columns" = Table.CombineColumns(Table.TransformColumnTypes(#"Renamed Columns", {{"Month", type text}, {"Day", type text}, {"Year", type text}}, "en-US"),{"Month", "Day", "Year"},Combiner.CombineTextByDelimiter("/", QuoteStyle.None),"Date"),
				    #"Changed Type1" = Table.TransformColumnTypes(#"Merged Columns",{{"Date", type datetime}, {"Corp Distributor Branch ID", type text}, {"Corp Distributor ID", type text}}),
				    #"Changed Type2" = Table.TransformColumnTypes(#"Changed Type1",{{"Date", type date}})
				in
				    #"Changed Type2"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

