table vn_calendar
	lineageTag: 05213079-ca58-48c5-9997-24187fe39f69

	column date
		dataType: dateTime
		formatString: Long Date
		lineageTag: 951d375b-459a-41d3-a0fc-b18f97617d75
		summarizeBy: none
		sourceColumn: date

		variation Variation
			isDefault
			relationship: 6d597ffc-250e-40c1-9e32-d24e052fe1db
			defaultHierarchy: LocalDateTable_6bf67dc3-4308-4f5f-a80c-06c216cb9868.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column yearmonth
		dataType: string
		lineageTag: 6febacc8-c793-4a7d-9ad5-c7b92e9fe0b2
		summarizeBy: none
		sourceColumn: yearmonth

		annotation SummarizationSetBy = Automatic

	column year
		dataType: string
		lineageTag: 15344fa2-d356-4930-a20d-8f56af1104d0
		summarizeBy: none
		sourceColumn: year

		annotation SummarizationSetBy = Automatic

	column year_fiscal
		dataType: string
		lineageTag: a7c65628-9cf4-4e55-a68b-aa575fc764a6
		summarizeBy: none
		sourceColumn: year_fiscal

		annotation SummarizationSetBy = Automatic

	column month
		dataType: string
		lineageTag: c889fcc3-b070-482f-bd74-edf38dc9f012
		summarizeBy: none
		sourceColumn: month

		annotation SummarizationSetBy = Automatic

	column month_fiscal
		dataType: string
		lineageTag: ddd188e4-31c9-4c03-bf07-139f8398b79c
		summarizeBy: none
		sourceColumn: month_fiscal

		annotation SummarizationSetBy = Automatic

	column quarter
		dataType: string
		lineageTag: 6868e04c-6566-4fe7-876a-442553549c50
		summarizeBy: none
		sourceColumn: quarter

		annotation SummarizationSetBy = Automatic

	column day
		dataType: string
		lineageTag: 360e58f1-5846-45ab-9ad1-3c5ec41280fa
		summarizeBy: none
		sourceColumn: day

		annotation SummarizationSetBy = Automatic

	column day_name
		dataType: string
		lineageTag: 240d5d40-cbc6-44f6-a62a-bfae817b099b
		summarizeBy: none
		sourceColumn: day_name

		annotation SummarizationSetBy = Automatic

	column Weekday = WEEKDAY(vn_calendar[date])
		formatString: 0
		lineageTag: 91e750cf-540a-4701-904b-fb3a6e17a75f
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

	partition vn_calendar = m
		mode: import
		queryGroup: Dimension
		source =
				let
				    Source = Databricks.Catalogs(#"Prod Server", #"Prod HTTP Path", [Catalog=null, Database=null, EnableAutomaticProxyDiscovery=null]),
				    cdl_amhq_prod_Database = Source{[Name = "cdl_amhq_prod",Kind="Database"]}[Data],
				    msv_workbench_Schema = cdl_amhq_prod_Database{[Name="nexa_msv_workbench_gold",Kind="Schema"]}[Data],
				    vn_calendar_Table = msv_workbench_Schema{[Name="vn_calendar",Kind="Table"]}[Data],
				    #"Removed Columns" = Table.RemoveColumns(vn_calendar_Table,{"update_date", "insert_date", "ama_last_processed_date"})
				in
				    #"Removed Columns"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

