table vn_direct_shipment_target_fct
	lineageTag: 15cc21a0-b974-46e3-ab13-f4664f4d460d

	column prod_key
		dataType: string
		lineageTag: 611e104e-f105-4d74-a7ef-594cfece3a44
		summarizeBy: none
		sourceColumn: prod_key

		annotation SummarizationSetBy = Automatic

	column cust_key
		dataType: string
		lineageTag: ef14f3c5-d30d-4fee-badf-2fb859a327cd
		summarizeBy: none
		sourceColumn: cust_key

		annotation SummarizationSetBy = Automatic

	column msu_target
		dataType: double
		lineageTag: f74dcb53-e138-40be-8459-75a177cd619b
		summarizeBy: sum
		sourceColumn: msu_target

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column giv_target
		dataType: double
		lineageTag: 5d3eefcd-1d01-4507-bade-b0c6562656fd
		summarizeBy: sum
		sourceColumn: giv_target

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column year_month
		dataType: string
		lineageTag: ce61c9b8-c213-429a-b841-c0dea7e16618
		summarizeBy: none
		sourceColumn: year_month

		annotation SummarizationSetBy = Automatic

	column date = DATE(LEFT(vn_direct_shipment_target_fct[year_month], 4), RIGHT(vn_direct_shipment_target_fct[year_month],2),1)
		formatString: Short Date
		lineageTag: d87ede01-9940-4ea9-b244-4defbabc7b1e
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	partition vn_direct_shipment_target_fct = m
		mode: import
		queryGroup: Fact
		source =
				let
				    Source = PowerPlatform.Dataflows(null),
				    Workspaces = Source{[Id="Workspaces"]}[Data],
				    #"d5309721-c5fc-4d37-924d-0b134d285358" = Workspaces{[workspaceId="d5309721-c5fc-4d37-924d-0b134d285358"]}[Data],
				    #"94fdff2d-0c6e-493b-a710-c0a15a49e269" = #"d5309721-c5fc-4d37-924d-0b134d285358"{[dataflowId="94fdff2d-0c6e-493b-a710-c0a15a49e269"]}[Data],
				    vn_direct_shipment_target_fct_ = #"94fdff2d-0c6e-493b-a710-c0a15a49e269"{[entity="vn_direct_shipment_target_fct",version=""]}[Data],
				    #"Changed Type" = Table.TransformColumnTypes(vn_direct_shipment_target_fct_,{{"prod_key", type text}, {"cust_key", type text}, {"year_month", type text}, {"msu_target", type number}, {"giv_target", type number}})
				in
				    #"Changed Type"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

