table vn_direct_shipment_fct
	lineageTag: 36495ff9-73ca-446f-9e2c-98211cd417a5

	column data_provider_key
		dataType: string
		lineageTag: ee24d9c8-2304-4228-95b6-038b6e4f8cb8
		summarizeBy: none
		sourceColumn: data_provider_key

		annotation SummarizationSetBy = Automatic

	column day_date
		dataType: dateTime
		formatString: Long Date
		lineageTag: 71351993-3799-4865-946a-40cc7627c229
		summarizeBy: none
		sourceColumn: day_date

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column prod_key
		dataType: string
		lineageTag: a56263cc-4e4b-47e1-a699-106bb7030926
		summarizeBy: none
		sourceColumn: prod_key

		annotation SummarizationSetBy = Automatic

	column shipment_giv_value
		dataType: double
		lineageTag: f3556f17-fca6-45ae-9b09-71876bff4da2
		summarizeBy: sum
		sourceColumn: shipment_giv_value

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column store_key
		dataType: string
		lineageTag: baf822b0-6be0-4d16-bf41-601e6c753090
		summarizeBy: none
		sourceColumn: store_key

		annotation SummarizationSetBy = Automatic

	column cust_key
		dataType: string
		lineageTag: cc568db7-5a34-4aff-a8a1-7cd5ea516352
		summarizeBy: none
		sourceColumn: cust_key

		annotation SummarizationSetBy = Automatic

	column shipment_su
		dataType: double
		lineageTag: 91dea850-209d-4314-900a-08389b8f0565
		summarizeBy: sum
		sourceColumn: shipment_su

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	partition vn_direct_shipment_fct = m
		mode: import
		queryGroup: Fact
		source =
				let
				    Source = PowerPlatform.Dataflows(null),
				    Workspaces = Source{[Id="Workspaces"]}[Data],
				    #"d5309721-c5fc-4d37-924d-0b134d285358" = Workspaces{[workspaceId="d5309721-c5fc-4d37-924d-0b134d285358"]}[Data],
				    #"94fdff2d-0c6e-493b-a710-c0a15a49e269" = #"d5309721-c5fc-4d37-924d-0b134d285358"{[dataflowId="94fdff2d-0c6e-493b-a710-c0a15a49e269"]}[Data],
				    vn_direct_shipment_fct_ = #"94fdff2d-0c6e-493b-a710-c0a15a49e269"{[entity="vn_direct_shipment_fct",version=""]}[Data],
				    #"Removed Other Columns" = Table.SelectColumns(vn_direct_shipment_fct_,{"data_provider_key", "day_date", "prod_key", "shipment_giv_value", "shipment_su", "store_key", "cust_key"}),
				    #"Changed Type" = Table.TransformColumnTypes(#"Removed Other Columns",{{"data_provider_key", type text}, {"prod_key", type text}, {"store_key", type text}, {"cust_key", type text}, {"day_date", type date}})
				in
				    #"Changed Type"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Exception

