table vn_indirect_target_brand_distributor
	lineageTag: abc84bcd-162d-441e-82bf-9846aed54d4d

	column year_month
		dataType: string
		lineageTag: 706f0245-2422-4a29-bbde-ae952de25876
		summarizeBy: none
		sourceColumn: year_month

		annotation SummarizationSetBy = Automatic

	column local_customer_name
		dataType: string
		lineageTag: d16ba5a9-3ef3-4f5c-8d83-42aee64ad74e
		summarizeBy: none
		sourceColumn: local_customer_name

		annotation SummarizationSetBy = Automatic

	column local_brand_name
		dataType: string
		lineageTag: 27e495f6-7650-4d03-8b21-93e4a72996ba
		summarizeBy: none
		sourceColumn: local_brand_name

		annotation SummarizationSetBy = Automatic

	column sales_target
		dataType: int64
		formatString: 0
		lineageTag: e582f2ba-380b-4117-b704-a3bac7fde913
		summarizeBy: sum
		sourceColumn: sales_target

		annotation SummarizationSetBy = Automatic

	column sub_channel =
			
			SWITCH(
			    TRUE(),
			    CONTAINSSTRING(vn_indirect_target_brand_distributor[local_customer_name], "PHU THAI"), "Phu Thai",
			    CONTAINSSTRING(vn_indirect_target_brand_distributor[local_customer_name], "DAC HUNG"), "Dac Hung",
			    CONTAINSSTRING(vn_indirect_target_brand_distributor[local_customer_name], "TUAN VIET"), "Tuan Viet",
			    CONTAINSSTRING(vn_indirect_target_brand_distributor[local_customer_name], "MESA"), "Mesa")
		lineageTag: bb91caaf-a70c-44ac-bf2d-1f1b0c72b6c8
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column date = DATE(left(vn_indirect_target_brand_distributor[year_month], 4), RIGHT(vn_indirect_target_brand_distributor[year_month],2),1)
		formatString: Short Date
		lineageTag: dfc109c5-c7a8-4ff5-8519-7bbb374f9716
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	partition vn_indirect_target_brand_distributor = m
		mode: import
		queryGroup: Fact
		source =
				let
				    Source = Databricks.Catalogs(#"Prod Server", #"Prod HTTP Path", [Catalog=null, Database=null, EnableAutomaticProxyDiscovery=null]),
				    cdl_amhq_prod_Database = Source{[Name = "cdl_amhq_prod",Kind="Database"]}[Data],
				    nexa_msv_workbench_gold_Schema = cdl_amhq_prod_Database{[Name="nexa_msv_workbench_gold",Kind="Schema"]}[Data],
				    vn_indirect_target_brand_distributor_Table = nexa_msv_workbench_gold_Schema{[Name="vn_indirect_target_brand_distributor",Kind="Table"]}[Data],
				    #"Removed Other Columns" = Table.SelectColumns(vn_indirect_target_brand_distributor_Table,{"year_month", "local_customer_name", "local_brand_name", "sales_target"}),
				    #"Removed Duplicates" = Table.Distinct(#"Removed Other Columns")
				in
				    #"Removed Duplicates"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

