table vn_indirect_shipment_fct
	lineageTag: 79717cbe-3b8c-471c-8d05-3b604f67cccc

	column cust_key
		dataType: string
		lineageTag: 8df4ecbc-9ee2-47d6-af46-92ddc0a357b3
		summarizeBy: none
		sourceColumn: cust_key

		annotation SummarizationSetBy = Automatic

	column data_provider_key
		dataType: string
		lineageTag: 2e17db27-f1b7-4995-a933-f3a20b5d3d5c
		summarizeBy: none
		sourceColumn: data_provider_key

		annotation SummarizationSetBy = Automatic

	column day_date
		dataType: dateTime
		formatString: Long Date
		lineageTag: 3b00be4a-ae0c-4ae9-8e21-80ca9e36d0fe
		summarizeBy: none
		sourceColumn: day_date

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column indirect_giv_shipment
		dataType: double
		lineageTag: fa86f853-ecec-40c5-aeba-96a245514832
		summarizeBy: sum
		sourceColumn: indirect_giv_shipment

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column prod_key
		dataType: string
		lineageTag: 9d57e4a7-f482-40b7-bf0a-3a9dcd9fe37d
		summarizeBy: none
		sourceColumn: prod_key

		annotation SummarizationSetBy = Automatic

	column store_key
		dataType: string
		lineageTag: 15b430f3-c4e9-4586-9d34-9c12d9e6321a
		summarizeBy: none
		sourceColumn: store_key

		annotation SummarizationSetBy = Automatic

	column branch_key
		dataType: string
		lineageTag: 91a31a3f-3cbb-4611-8849-6992e18e20d2
		summarizeBy: none
		sourceColumn: branch_key

		annotation SummarizationSetBy = Automatic

	column key_qdgp =
			
			VAR _local_channel = LOOKUPVALUE( dim_indirect_store[region_localchannel] , dim_indirect_store[pr_key], vn_indirect_shipment_fct[store_key] )
			VAR _year_month = RELATED( vn_calendar[yearmonth])
			VAR _fpd_id = LOOKUPVALUE( dim_product[fpc_id] , dim_product[prod_key], vn_indirect_shipment_fct[prod_key])
			RETURN
			_year_month&"_"&_local_channel&"_"&_fpd_id
		lineageTag: b011273b-f9b4-468c-800f-cdb91762fa7f
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column key_qdgp_group =
			
			VAR _local_channel = LOOKUPVALUE( dim_indirect_store[region_localchannel] , dim_indirect_store[pr_key], vn_indirect_shipment_fct[store_key] )
			VAR _year_month = RELATED( vn_calendar[yearmonth])
			VAR _group = RELATED(fct_qdgp[GroupName])
			RETURN
			_year_month&"_"&_local_channel&"_"&_group
		lineageTag: 3702cf3f-98ea-4971-9290-639489f94228
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column qdgp_hit = ```
			
			VAR _QDGP_Sum_Unit = 
			CALCULATE(
			    SUM(vn_indirect_shipment_fct[Indirect_Unit_Shipments]),
			    ALLEXCEPT(vn_indirect_shipment_fct,vn_indirect_shipment_fct[store_key],vn_indirect_shipment_fct[key_qdgp_group]))
			VAR _QDGP_MOQ = 
			CALCULATE(
			    SELECTEDVALUE(fct_qdgp[MOQ (IT)]),
			    ALLEXCEPT(fct_qdgp,fct_qdgp[QDGP_Group_Key],fct_qdgp[GroupName],fct_qdgp[MOQ (IT)]))    
			RETURN 
			IF(ISBLANK(_QDGP_MOQ),BLANK(),  
			      IF(ROUND(_QDGP_Sum_Unit,0) >=VALUE(_QDGP_MOQ),1,0))
			```
		formatString: 0
		lineageTag: dada968c-acb7-4564-a515-71a9ddf8faf4
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

	column Indirect_Unit_Shipments
		dataType: double
		lineageTag: 14921f9d-31ef-44cd-b57d-22944d1b7069
		summarizeBy: sum
		sourceColumn: Indirect_Unit_Shipments

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Invoice_ID
		dataType: string
		lineageTag: 4e31b8b2-528e-45b3-b6c8-17d7caf4e5c9
		summarizeBy: none
		sourceColumn: Invoice_ID

		annotation SummarizationSetBy = Automatic

	column bill_id = vn_indirect_shipment_fct[branch_key] & vn_indirect_shipment_fct[day_date] & vn_indirect_shipment_fct[Invoice_ID]
		lineageTag: 6c45cde9-6460-4756-896d-c97fee6c932f
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column store_key_hist =
			
			VAR _date = vn_indirect_shipment_fct[day_date]
			VAR _store = vn_indirect_shipment_fct[store_key]
			
			VAR _before =
			    CALCULATE(
			        MAX(dim_indirect_store_hist[begin_date]),
			        FILTER(
			            dim_indirect_store_hist,
			            dim_indirect_store_hist[store_id] = _store
			                && dim_indirect_store_hist[begin_date] <= _date
			        )
			    )
			
			VAR _after =
			    CALCULATE(
			        MIN(dim_indirect_store_hist[begin_date]),
			        FILTER(
			            dim_indirect_store_hist,
			            dim_indirect_store_hist[store_id] = _store
			                && dim_indirect_store_hist[begin_date] > _date
			        )
			    )
			
			VAR _closest =
			    IF(
			        NOT ISBLANK(_before),
			        _before,       -- ưu tiên after
			        _after       -- chỉ lấy before khi after blank
			    )
			
			RETURN
			    CALCULATE(
			        MAX(dim_indirect_store_hist[store_key]),
			        FILTER(
			            dim_indirect_store_hist,
			            dim_indirect_store_hist[store_id] = _store
			                && dim_indirect_store_hist[begin_date] = _closest
			        )
			    )
		lineageTag: ac9bc8b7-f38f-4ad2-8d66-32c3960ebd6f
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	partition vn_indirect_shipment_fct = m
		mode: import
		queryGroup: Fact
		source =
				let
				    Source = Databricks.Catalogs(#"Prod Server", #"Prod HTTP Path", [Catalog=null, Database=null, EnableAutomaticProxyDiscovery=null]),
				    cdl_amhq_prod_Database = Source{[Name = "cdl_amhq_prod",Kind="Database"]}[Data],
				    nexa_msv_workbench_gold_Schema = cdl_amhq_prod_Database{[Name="nexa_msv_workbench_gold",Kind="Schema"]}[Data],
				    vn_indirect_shipment_fct_Table = nexa_msv_workbench_gold_Schema{[Name="vn_indirect_shipment_fct",Kind="Table"]}[Data],
				    #"Removed Other Columns" = Table.SelectColumns(vn_indirect_shipment_fct_Table,{"Invoice_ID", "cust_key", "data_provider_key", "day_date", "indirect_giv_shipment", "Indirect_Unit_Shipments", "prod_key", "store_key", "branch_key"}),
				    #"Changed Type" = Table.TransformColumnTypes(#"Removed Other Columns",{{"branch_key", type text}, {"data_provider_key", type text}, {"cust_key", type text}, {"store_key", type text}, {"prod_key", type text}})
				in
				    #"Changed Type"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Exception

