table vn_indirect_coverage
	lineageTag: 41c17094-2195-4efb-afee-71958296bbef

	column coverage_ind_L1M
		dataType: int64
		formatString: 0
		lineageTag: ac8d8a0d-db00-488a-b6e0-5421b2b5d68f
		summarizeBy: sum
		sourceColumn: coverage_ind_L1M

		annotation SummarizationSetBy = Automatic

	column coverage_ind_L3M
		dataType: int64
		formatString: 0
		lineageTag: 665691ac-ba82-4c60-b610-bca362220b43
		summarizeBy: sum
		sourceColumn: coverage_ind_L3M

		annotation SummarizationSetBy = Automatic

	column cust_key
		dataType: string
		lineageTag: a8d0edee-7436-4de0-9ef1-d0aad0dc0f41
		summarizeBy: none
		sourceColumn: cust_key

		changedProperty = DataType

		annotation SummarizationSetBy = Automatic

	column day_date
		dataType: dateTime
		formatString: Short Date
		lineageTag: 2f040791-a24d-439f-98f6-610d8221d852
		summarizeBy: none
		sourceColumn: day_date

		annotation SummarizationSetBy = Automatic

	column store_key
		dataType: string
		lineageTag: d24a8303-4de5-40ea-ae26-3f232ca7b1ed
		summarizeBy: none
		sourceColumn: store_key

		annotation SummarizationSetBy = Automatic

	column update_date
		dataType: dateTime
		formatString: General Date
		lineageTag: 34512886-38ad-42d2-9643-4bac9071b052
		summarizeBy: none
		sourceColumn: update_date

		variation Variation
			isDefault
			relationship: 83fdb51a-f175-4d93-82dc-1d2e4664159f
			defaultHierarchy: LocalDateTable_87ec4d1b-66ce-47e2-93b5-e8d7eb9d1e55.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	column insert_date
		dataType: dateTime
		formatString: General Date
		lineageTag: b5479f13-626a-4ef1-a5ea-2b7a048f5351
		summarizeBy: none
		sourceColumn: insert_date

		variation Variation
			isDefault
			relationship: 5ad47c46-d583-4987-9322-072810977cb9
			defaultHierarchy: LocalDateTable_e251f496-08b5-415f-97cc-958dbda9631d.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	column ama_last_processed_date
		dataType: dateTime
		formatString: General Date
		lineageTag: 666ef152-4ad6-454d-ab55-03d9d605e710
		summarizeBy: none
		sourceColumn: ama_last_processed_date

		variation Variation
			isDefault
			relationship: 7244ddc4-df64-491c-8d76-6c9d6513b33f
			defaultHierarchy: LocalDateTable_d901be79-89eb-4ff7-a72c-3f3ae1ec7269.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	partition vn_indirect_coverage = m
		mode: import
		queryGroup: Fact
		source =
				let
				    Source = Databricks.Catalogs(#"Prod Server", #"Prod HTTP Path", [Catalog=null, Database=null, EnableAutomaticProxyDiscovery=null]),
				    cdl_amhq_prod_Database = Source{[Name = "cdl_amhq_prod",Kind="Database"]}[Data],
				    nexa_msv_workbench_gold_Schema = cdl_amhq_prod_Database{[Name="nexa_msv_workbench_gold",Kind="Schema"]}[Data],
				    vn_indirect_coverage = nexa_msv_workbench_gold_Schema{[Name="vn_indirect_coverage",Kind="Table"]}[Data],
				    #"Changed Type" = Table.TransformColumnTypes(vn_indirect_coverage,{{"store_key", type text}}),
				    #"Removed Other Columns" = Table.SelectColumns(#"Changed Type",{"coverage_ind_L1M", "coverage_ind_L3M", "cust_key", "day_date", "store_key", "update_date", "insert_date", "ama_last_processed_date"})
				in
				    #"Removed Other Columns"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

