table vn_pos_coop
	lineageTag: 756161e3-4969-4b9f-b542-6b577d7148f3

	column gtin_code
		dataType: string
		lineageTag: ccd4399c-df90-420a-98cc-238fd73ded4b
		summarizeBy: none
		sourceColumn: gtin_code

		annotation SummarizationSetBy = Automatic

	column product_name
		dataType: string
		lineageTag: ace1b73f-cfe6-4220-823a-0978bc36b594
		summarizeBy: none
		sourceColumn: product_name

		annotation SummarizationSetBy = Automatic

	column store_name
		dataType: string
		lineageTag: 17173485-7b9c-4843-9db1-05d34d2ebaa0
		summarizeBy: none
		sourceColumn: store_name

		annotation SummarizationSetBy = Automatic

	column date
		dataType: dateTime
		formatString: Long Date
		lineageTag: d2486acf-a34f-4a0e-9627-4bb34b3b89c5
		summarizeBy: none
		sourceColumn: date

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column sales_qty
		dataType: double
		lineageTag: 663cd714-aa32-4478-83f9-e34124a8e993
		summarizeBy: sum
		sourceColumn: sales_qty

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column store_code
		dataType: string
		lineageTag: 1ca0d249-9f58-493e-90b7-e93ae4884493
		summarizeBy: none
		sourceColumn: store_code

		annotation SummarizationSetBy = Automatic

	column sales_value
		dataType: double
		lineageTag: 9c2e4656-9a2b-41a8-ad6e-608d0806a9be
		summarizeBy: sum
		sourceColumn: sales_value

		changedProperty = DataType

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column data_provider_key
		dataType: string
		lineageTag: 2dd01c79-c2ca-441c-9a23-37424c933186
		summarizeBy: none
		sourceColumn: data_provider_key

		annotation SummarizationSetBy = Automatic

	column key = vn_pos_coop[store_code]&"HSM"
		lineageTag: a18a76aa-0ba7-4da0-98b3-9b1c875a943e
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	partition vn_pos_coop = m
		mode: import
		queryGroup: POS
		source =
				let
				    Source = PowerPlatform.Dataflows(null),
				    Workspaces = Source{[Id="Workspaces"]}[Data],
				    #"d5309721-c5fc-4d37-924d-0b134d285358" = Workspaces{[workspaceId="d5309721-c5fc-4d37-924d-0b134d285358"]}[Data],
				    #"9ed41e68-6fd6-406c-aaed-cf8719043a3e" = #"d5309721-c5fc-4d37-924d-0b134d285358"{[dataflowId="9ed41e68-6fd6-406c-aaed-cf8719043a3e"]}[Data],
				    vn_pos_coop_monthly_dataflow_ = #"9ed41e68-6fd6-406c-aaed-cf8719043a3e"{[entity="vn_pos_coop_monthly_dataflow",version=""]}[Data],
				    #"Changed Type" = Table.TransformColumnTypes(vn_pos_coop_monthly_dataflow_,{{"customer_prod_id", type text}, {"gtin_item", type text}, {"store_code", type text}, {"product_name", type text}, {"store_name", type text}}),
				    #"Added Custom" = Table.AddColumn(#"Changed Type", "key", each "SGC_"&[store_code]),
				    #"Removed Columns" = Table.RemoveColumns(#"Added Custom",{"store_code", "customer_prod_id"}),
				    #"Added Custom2" = Table.AddColumn(#"Removed Columns", "Custom", each [sales_value] * 1.08),
				    #"Removed Columns1" = Table.RemoveColumns(#"Added Custom2",{"sales_value"}),
				    #"Renamed Columns" = Table.RenameColumns(#"Removed Columns1",{{"key", "store_code"}, {"gtin_item", "gtin_code"}, {"sales_quantity", "sales_qty"}, {"Custom", "sales_value"}}),
				    #"Added Custom1" = Table.AddColumn(#"Renamed Columns", "data_provider_key", each "SGC")
				in
				    #"Added Custom1"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

