table vn_pos_monthly
	lineageTag: 4eb145f6-6c77-4de9-929a-9f850c853fae

	column prod_key
		dataType: string
		lineageTag: b6035653-e09c-400f-9b3a-bd260bcf63c4
		summarizeBy: none
		sourceColumn: prod_key

		annotation SummarizationSetBy = Automatic

	column store_id
		dataType: string
		lineageTag: 0f11e0ee-aa17-45e9-96b5-cd40035a19a6
		summarizeBy: none
		sourceColumn: store_id

		annotation SummarizationSetBy = Automatic

	column data_provider_key
		dataType: string
		lineageTag: 62df1289-1dfb-43d8-a70b-e4e67d567a7f
		summarizeBy: none
		sourceColumn: data_provider_key

		annotation SummarizationSetBy = Automatic

	column sales_qty
		dataType: double
		lineageTag: cfa1a748-e5fb-4b69-9b7c-a6a70d2fbde4
		summarizeBy: sum
		sourceColumn: sales_qty

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column closing_value
		dataType: double
		lineageTag: 0f321c28-7d74-4a33-af55-d1bb764d1afb
		summarizeBy: sum
		sourceColumn: closing_value

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column closing_qty
		dataType: double
		lineageTag: cb0377dd-1942-4161-92da-4af22d92cdd3
		summarizeBy: sum
		sourceColumn: closing_qty

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column sub_channel =
			
			SWITCH(
			    TRUE(),
			    vn_pos_monthly[data_provider_key] = "10000101724280", "Winmart",
			    vn_pos_monthly[data_provider_key] = "10000101759516", "Aeon",
			    vn_pos_monthly[data_provider_key] = "10000101759517", "Mega Market",
			    vn_pos_monthly[data_provider_key] = "10000101724279", "Coop",
			    vn_pos_monthly[data_provider_key] = "10000101759543", "Emart",
			    vn_pos_monthly[data_provider_key] = "10000101752637", "Bach Hoa Xanh",
			    vn_pos_monthly[data_provider_key] = "10000101759522", "Lotte",
			    vn_pos_monthly[data_provider_key] = "10000101759579", "Guardian",
			    "Others"
			)
		lineageTag: 23cffbf1-7ba4-4801-b91a-0fb222b4af50
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column sales_value
		dataType: double
		lineageTag: d8e6aa85-4757-4de9-bd10-58c5e3891f0c
		summarizeBy: sum
		sourceColumn: sales_value

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column store_code =
			
			LOOKUPVALUE(
			    vn_pos_store_dim_vw[pos_store_code],
			    vn_pos_store_dim_vw[pos_store_key],
			    vn_pos_monthly[store_id]
			)
		lineageTag: 51ca8819-83eb-4fb3-945d-4a4eb7183c42
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column date
		dataType: dateTime
		formatString: Long Date
		lineageTag: a283961c-0e64-4e92-b5bd-d218c65b9140
		summarizeBy: none
		sourceColumn: date

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column key_prod_prov
		dataType: string
		lineageTag: f36d424c-52ef-4d23-accf-0735f6ffb406
		summarizeBy: none
		sourceColumn: key_prod_prov

		annotation SummarizationSetBy = Automatic

	column gtin_item
		dataType: string
		lineageTag: 7d203f09-081b-44d2-a4ed-95c738737de8
		summarizeBy: none
		sourceColumn: gtin_item

		annotation SummarizationSetBy = Automatic

	column year_month_no =
			
			YEAR(vn_pos_monthly[date]) * 100 + MONTH(vn_pos_monthly[date])
		formatString: 0
		lineageTag: b0e3faee-d255-4fc8-996f-dd715a6d0e52
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

	partition vn_pos_monthly = m
		mode: import
		queryGroup: POS
		source = ```
				let
				    Source = Databricks.Catalogs(#"Prod Server", #"Prod HTTP Path", [Catalog=null, Database=null, EnableAutomaticProxyDiscovery=null]),
				    cdl_amhq_prod_Database = Source{[Name = "cdl_amhq_prod",Kind="Database"]}[Data],
				    nexa_msv_workbench_gold_Schema = cdl_amhq_prod_Database{[Name="nexa_msv_workbench_gold",Kind="Schema"]}[Data],
				    vn_pos_monthly_fact_Table = nexa_msv_workbench_gold_Schema{[Name="vn_pos_monthly_fact",Kind="Table"]}[Data],
				    #"Changed Type" = Table.TransformColumnTypes(vn_pos_monthly_fact_Table,{{"store_key", type text}, {"data_provider_key", Int64.Type}}),
				    #"Changed Type1" = Table.TransformColumnTypes(#"Changed Type",{{"data_provider_key", type text}, {"prod_key", type text}}),
				    #"Added Conditional Column" = Table.AddColumn(
				    #"Changed Type1",
				    "Custom",
				    each 
				        if List.Contains({"10000101752637", "10000101759517"}, [data_provider_key]) 
				        then [sales_value]
				        else if List.Contains({"10000101724280"}, [data_provider_key])
				        then [sales_value] * 1.1
				        else [sales_value] * 1.08
				),
				    #"Added Custom" = Table.AddColumn(#"Added Conditional Column",
				    "date",
				    each #date(
				        Number.FromText(Text.Start([year_month], 4)),
				        Number.FromText(Text.End([year_month], 2)),
				        1
				    ),
				    type date
				),
				    #"Removed Columns" = Table.RemoveColumns(#"Added Custom",{"update_date", "insert_date", "ama_last_processed_date", "sales_value", "year_month"}),
				    #"Renamed Columns" = Table.RenameColumns(#"Removed Columns",{{"Custom", "sales_value"}, {"store_key", "store_id"}, {"sales_quantity", "sales_qty"}, {"inventory_value", "closing_value"}, {"inventory_quantity", "closing_qty"}}),
				    #"Changed Type2" = Table.TransformColumnTypes(#"Renamed Columns",{{"sales_value", type number}}),
				    #"Added Custom1" = Table.AddColumn(#"Changed Type2", "key_prod_prov", each [prod_key]&[data_provider_key]),
				    #"Merged Queries" = Table.NestedJoin(#"Added Custom1", {"key_prod_prov"}, dim_pos_product, {"key"}, "dim_pos_product", JoinKind.LeftOuter),
				    #"Expanded dim_pos_product" = Table.ExpandTableColumn(#"Merged Queries", "dim_pos_product", {"item_gtin"}, {"gtin_item"})
				in
				    #"Expanded dim_pos_product"
				```

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Exception

