table vn_pos_crv
	lineageTag: e6668ead-44cc-4d3c-b3ee-bea7f97885ff

	column store_code
		dataType: string
		lineageTag: 502d1de6-d354-45b0-9e15-f526f72d3ba1
		summarizeBy: none
		sourceColumn: store_code

		annotation SummarizationSetBy = Automatic

	column store_name
		dataType: string
		lineageTag: d0ab807c-f917-440d-8696-c0f6862cf413
		summarizeBy: none
		sourceColumn: store_name

		annotation SummarizationSetBy = Automatic

	column closing_qty
		dataType: double
		lineageTag: 07aadf77-d9fc-4f2b-9a2e-f79a741c6faf
		summarizeBy: sum
		sourceColumn: closing_qty

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column closing_value
		dataType: double
		lineageTag: bbf8a40a-3895-41fd-a23d-700fe4c7a0c6
		summarizeBy: sum
		sourceColumn: closing_value

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column sales_qty
		dataType: int64
		formatString: 0
		lineageTag: 70c0c332-03b3-4991-a7a8-022408607f49
		summarizeBy: sum
		sourceColumn: sales_qty

		annotation SummarizationSetBy = Automatic

	column gtin_code
		dataType: string
		lineageTag: f283b55f-bd13-40c0-87cc-2fe3bc2000f0
		summarizeBy: none
		sourceColumn: gtin_code

		annotation SummarizationSetBy = Automatic

	column prod_cat
		dataType: string
		lineageTag: 1de7130c-a5ee-42b4-a7f6-3a169a940d8f
		summarizeBy: none
		sourceColumn: prod_cat

		annotation SummarizationSetBy = Automatic

	column date
		dataType: dateTime
		formatString: Long Date
		lineageTag: 63b1e093-3893-4b4c-91cf-17fae96b704a
		summarizeBy: none
		sourceColumn: date

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column sales_value
		dataType: double
		lineageTag: 4bc79291-6df0-4b73-879c-0b805475821f
		summarizeBy: sum
		sourceColumn: sales_value

		changedProperty = DataType

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column data_provider_key
		dataType: string
		lineageTag: 259810bf-9c85-4f93-9bc6-07443f6e3e85
		summarizeBy: none
		sourceColumn: data_provider_key

		annotation SummarizationSetBy = Automatic

	column key = vn_pos_crv[store_code]&"HSM"
		lineageTag: 9a1b454e-c13c-4251-bf2e-6e909c56678a
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	partition vn_pos_crv = m
		mode: import
		queryGroup: POS
		source =
				let
				    Source = PowerPlatform.Dataflows(null),
				    Workspaces = Source{[Id="Workspaces"]}[Data],
				    #"d5309721-c5fc-4d37-924d-0b134d285358" = Workspaces{[workspaceId="d5309721-c5fc-4d37-924d-0b134d285358"]}[Data],
				    #"cf23be40-c1ab-4c9b-89a0-4e14f4631b90" = #"d5309721-c5fc-4d37-924d-0b134d285358"{[dataflowId="cf23be40-c1ab-4c9b-89a0-4e14f4631b90"]}[Data],
				    vn_pos_crv_fct_ = #"cf23be40-c1ab-4c9b-89a0-4e14f4631b90"{[entity="vn_pos_crv_fct",version=""]}[Data],
				    #"Filtered Rows" = Table.SelectRows(vn_pos_crv_fct_, each [Month] <> null and [Month] <> ""),
				    #"Changed Type" = Table.TransformColumnTypes(#"Filtered Rows",{{"Month", type text}, {"Store code", type text}, {"Store name", type text}, {"Product ID", type text}, {"Barcode", type text}, {"Cat", type text}, {"Closing Quantity", type number}, {"Closing Value", type number}}),
				    #"Added Custom" = Table.AddColumn(
				    #"Changed Type",
				    "date",
				    each #date(
				        Number.FromText(Text.Start([Month], 4)),
				        Number.FromText(Text.End([Month], 2)),
				        1
				    ),
				    type date
				),
				    #"Added Custom2" = Table.AddColumn(#"Added Custom", "sales_value", each [Revenue]*1.08),
				    #"Removed Columns" = Table.RemoveColumns(#"Added Custom2",{"Source.Name", "Month", "Product ID","Revenue"}),
				    #"Renamed Columns" = Table.RenameColumns(#"Removed Columns",{{"Store code", "store_code"}, {"Store name", "store_name"}, {"Closing Quantity", "closing_qty"}, {"Closing Value", "closing_value"}, {"Sales Quantity", "sales_qty"}, {"Barcode", "gtin_code"}, {"Cat", "prod_cat"}}),
				    #"Added Custom1" = Table.AddColumn(#"Renamed Columns", "data_provider_key", each "CRV")
				in
				    #"Added Custom1"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

